//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice3.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllDataView
    {
        public string Название_эпизода { get; set; }
        public string Описание_эпизода { get; set; }
        public decimal Длительность__мл_сек_ { get; set; }
        public string Название_подкаста { get; set; }
        public string Описание_подкаста { get; set; }
        public string Название_альбома { get; set; }
        public string Описание_альбома { get; set; }
        public string Имя_автора { get; set; }
        public string Фамилия_автора { get; set; }
        public string Отчество__автора { get; set; }
        public string Псевдоним_автора { get; set; }
        public int Возраст_автора { get; set; }
    }
}
