//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice3.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllDataView
    {
        public string Author_name { get; set; }
        public string Author_Surname { get; set; }
        public string Author_patronymic { get; set; }
        public string Author_nickname { get; set; }
        public int Author_Age { get; set; }
        public string Podcast_name { get; set; }
        public string Podcast_Description { get; set; }
        public string Episode_name { get; set; }
        public string Episode_Description { get; set; }
        public decimal Duration__milliSeconds_ { get; set; }
        public string Album_name { get; set; }
        public string Album_description { get; set; }
    }
}
