//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Author()
        {
            this.Album = new HashSet<Album>();
            this.Podcast = new HashSet<Podcast>();
        }
    
        public int ID_Author { get; set; }
        public string Author_Name { get; set; }
        public string Author_SurName { get; set; }
        public string Author_Patronymic { get; set; }
        public string Author_Nickname { get; set; }
        public int Author_Age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album> Album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podcast> Podcast { get; set; }

        public override string ToString()
        {
            return $"{Author_SurName} {Author_Name.Substring(0, 1)}. {Author_Patronymic?.Substring(0, 1)} - {Author_Nickname}";
        }
    }
}
