//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PodcastDBContext : DbContext
    {
        public PodcastDBContext()
            : base("name=PodcastsPlaylistsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Album { get; set; }
        public virtual DbSet<AlbumsPodcasts> AlbumsPodcasts { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Episode> Episode { get; set; }
        public virtual DbSet<Podcast> Podcast { get; set; }
    }
}
